/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#004343",
        "tertiary-dim": "#834100",
        "surface-dim": "#d7dbdb",
        "error-dim": "#70030f",
        "on-error": "#fff7f6",
        "tertiary-fixed-dim": "#fc8f34",
        "secondary-container": "#ffdfa0",
        "tertiary-fixed": "#ffa35d",
        "primary-fixed": "#9eeae9",
        "on-surface-variant": "#5c6060",
        "inverse-surface": "#0c0f0f",
        "on-tertiary": "#fff7f4",
        "primary": "#106a6a",
        "inverse-on-surface": "#9c9d9d",
        "error": "#ac3434",
        "outline": "#777b7c",
        "surface-tint": "#106a6a",
        "on-primary-fixed-variant": "#006263",
        "surface-container-low": "#f3f4f4",
        "on-tertiary-container": "#592a00",
        "background": "#f9f9f9",
        "on-secondary-fixed-variant": "#765600",
        "primary-dim": "#005d5d",
        "outline-variant": "#afb2b3",
        "primary-container": "#9eeae9",
        "on-secondary-fixed": "#523c00",
        "on-primary": "#e0fffe",
        "surface-variant": "#e0e3e4",
        "inverse-primary": "#a9f6f5",
        "surface-bright": "#f9f9f9",
        "tertiary-container": "#ffa35d",
        "surface-container": "#eceeee",
        "secondary-fixed-dim": "#ffcd62",
        "surface": "#f9f9f9",
        "secondary-fixed": "#ffdfa0",
        "secondary": "#7a5a00",
        "surface-container-highest": "#e0e3e4",
        "on-error-container": "#65000b",
        "tertiary": "#954b00",
        "on-secondary-container": "#694d00",
        "on-surface": "#2f3334",
        "on-primary-container": "#005858",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#90dcdb",
        "on-tertiary-fixed": "#371800",
        "surface-container-high": "#e6e8e9",
        "on-background": "#2f3334",
        "on-secondary": "#fff8f1",
        "secondary-dim": "#6b4e00",
        "on-tertiary-fixed-variant": "#663100",
        "error-container": "#f56965",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
