export const CATEGORIES = [
  "Groceries",
  "Rent",
  "Utilities",
  "Dining",
  "Transportation",
  "Entertainment",
  "Healthcare",
  "Shopping",
  "Travel",
  "Payment",
  "Other",
  "Gas",
  "Car Insurance",
  "Car Maintenance",
  "Home Care",
  "Pet Care",
  "Pet Insurance",
  "Vet",
  "Gift",
  "Subscription",
  "Parking",
  "Tenant Insurance",
  "Reimbursement",
];

export const CATEGORY_ICONS = {
  Groceries: "shopping_cart",
  Rent: "home_work",
  Utilities: "bolt",
  Dining: "restaurant",
  Transportation: "directions_car",
  Entertainment: "subscriptions",
  Healthcare: "health_and_safety",
  Shopping: "shopping_bag",
  Travel: "flight_takeoff",
  Payment: "payments",
  Other: "more_horiz",
  Gas: "local_gas_station",
  "Car Insurance": "shield",
  "Car Maintenance": "build",
  "Home Care": "home_repair_service",
  "Pet Care": "pets",
  "Pet Insurance": "verified_user",
  Vet: "vaccines",
  Gift: "redeem",
  Subscription: "autorenew",
  Parking: "local_parking",
  "Tenant Insurance": "policy",
  Reimbursement: "currency_exchange",
};

export const CATEGORY_BG = {
  Groceries: "bg-primary-container text-on-primary-container",
  Rent: "bg-surface-container-high text-on-surface",
  Utilities: "bg-secondary-container text-on-secondary-container",
  Dining: "bg-tertiary-container text-on-tertiary-container",
  Transportation: "bg-primary-container text-on-primary-container",
  Entertainment: "bg-surface-container-highest text-on-surface-variant",
  Healthcare: "bg-primary-container text-on-primary-container",
  Shopping: "bg-secondary-container text-on-secondary-container",
  Travel: "bg-tertiary-container text-on-tertiary-container",
  Payment: "bg-surface-container-high text-on-surface",
  Other: "bg-surface-container-highest text-on-surface-variant",
  Gas: "bg-tertiary-container text-on-tertiary-container",
  "Car Insurance": "bg-secondary-container text-on-secondary-container",
  "Car Maintenance": "bg-surface-container-high text-on-surface",
  "Home Care": "bg-primary-container text-on-primary-container",
  "Pet Care": "bg-tertiary-container text-on-tertiary-container",
  "Pet Insurance": "bg-secondary-container text-on-secondary-container",
  Vet: "bg-primary-container text-on-primary-container",
  Gift: "bg-tertiary-container text-on-tertiary-container",
  Subscription: "bg-surface-container-highest text-on-surface-variant",
  Parking: "bg-surface-container-high text-on-surface",
  "Tenant Insurance": "bg-secondary-container text-on-secondary-container",
  Reimbursement: "bg-primary-container text-on-primary-container",
};